import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import {
  getMessages,
  unstable_setRequestLocale as setRequestLocale,
} from "next-intl/server";

import "../globals.css";
import { SiteHeader } from "@/components/site-header";
import { locales } from "@/i18n";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function RootLayout(
  props: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
  }
) {
  const params = await props.params;

  const {
    locale
  } = params;

  const {
    children
  } = props;

  setRequestLocale(locale);

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={cn(inter.className)}>
        <NextIntlClientProvider timeZone="Europe/Warsaw" messages={messages}>
          <header className="mx-auto flex max-w-7xl lg:px-8">
            <SiteHeader />
          </header>

          <main className="mx-auto flex max-w-7xl p-6 lg:px-8">{children}</main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
